var json = {
"User 1" :{
		"group":["Group:","On-Line Games"],
		"fname":["First name:","Howard"],
		"lname":["Last name:","Livingston"],
		"pword":["Password:","Alibubba123$"],
		"cpword":["Confirm Password:","Alibubba123$"],
		"email":["Email:","takeovertheworld.livingston7@gmail.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","Tablet"],
		"friends":["I have:","2"],
		"date":["Date:","June 2,2012"],
		"comments":["comments:","I wanna rock!"]
	},	
"User 2" :{
		"group":["Group:","On-Line Games"],
		"fname":["First name:","Tori"],
		"lname":["Last name:","Livingston"],
		"pword":["Password:","PanicAtTheDisco"],
		"cpword":["Confirm Password:","PanicAtTheDisco"],
		"email":["Email:","tnight47@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","phone"],
		"friends":["I have:","5"],
		"date":["Date:","November 10, 2011"],
		"comments":["comments:","I'm a pesky teenager"]
	},
"User 3" :{
		"group":["Group:","On-Line Games"],
		"fname":["First name:","Hannah"],
		"lname":["Last name:","Ilagan"],
		"pword":["Password:","PanicAtTheDisco"],
		"cpword":["Confirm Password:","PanicAtTheDisco"],
		"email":["Email:","kittensAndZombies@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","phone"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","yay me!"]
	},
"User 4" :{
		"group":["Group:","On-Line Games"],
		"fname":["First name:","Alley"],
		"lname":["Last name:","Livingston"],
		"pword":["Password:","Dungeons and Dragons"],
		"cpword":["Confirm Password:","PanicAtTheDisco"],
		"email":["Email:","kittensAndZombies@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","phone"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","These aren't the droids you're looking for!"]
	},
"User 5" :{
		"group":["Group:","Manual Games"],
		"fname":["First name:","Don"],
		"lname":["Last name:","The Dude"],
		"pword":["Password:","need food"],
		"cpword":["Confirm Password:","need food"],
		"email":["Email:","willplayforfood@aol.com"],
		"selectValue":["What do you want to do:","Play Opponent"],
		"deviceValue":["What device are you using:","tablet"],
		"friends":["I have:","0"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","Will play for food!"]
	},
"User 6" :{
		"group":["Group:","Console Games"],
		"fname":["First name:","Murph"],
		"lname":["Last name:","The Scurf"],
		"pword":["Password:","twinkies"],
		"cpword":["Confirm Password:","twinkies"],
		"email":["Email:","gimmefood@aol.com"],
		"selectValue":["What do you want to do:","PlayOpponent"],
		"deviceValue":["What device are you using:","tablet"],
		"friends":["I have:","1"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","I'm my own best friend!"]
	},
"User 7" :{
		"group":["Group:","Console Games"],
		"fname":["First name:","Bobby"],
		"lname":["Last name:","Burner"],
		"pword":["Password:","smokey"],
		"cpword":["Confirm Password:","smokey"],
		"email":["Email:","MaryJane@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","phone"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","I need munchies bro!"]
	},
"User 8" :{
		"group":["Group:","Console Games"],
		"fname":["First name:","Heather"],
		"lname":["Last name:","And that's all you need to know"],
		"pword":["Password:","RitzCarlton"],
		"cpword":["Confirm Password:","RitzCarlton"],
		"email":["Email:","MoreThanYou@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","phone"],
		"friends":["I have:","10,000"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","Send me a text!"]
	},
"User 9" :{
		"group":["Group:","Console Games"],
		"fname":["First name:","Mr."],
		"lname":["Last name:","Jones"],
		"pword":["Password:","Headhunter"],
		"cpword":["Confirm Password:","Headhunter"],
		"email":["Email:","wannajob@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","pc"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","Call me for a job!"]
	},
"User 10" :{
		"group":["Group:","Manual Games"],
		"fname":["First name:","Killer"],
		"lname":["Last name:","Kawalski"],
		"pword":["Password:","Crossbones"],
		"cpword":["Confirm Password:","Crossbones"],
		"email":["Email:","dontbe scared@aol.com"],
		"selectValue":["What do you want to do:","Computer Challenge"],
		"deviceValue":["What device are you using:","pc"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","The tides of war are breaking the dam!!"]
	},
"User 11" :{
		"group":["Group:","Phone Apps"],
		"fname":["First name:","Granny"],
		"lname":["Last name:","Gerta"],
		"pword":["Password:","Grandma"],
		"cpword":["Confirm Password:","Grandma"],
		"email":["Email:","loveInEveryStitch@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","pc"],
		"friends":["I have:","1"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","You'll love my cookies, but hate my punishment!"]
	},
"User 12" :{
		"group":["Group:","Phone Apps"],
		"fname":["First name:","Bob"],
		"lname":["Last name:","The mechanic"],
		"pword":["Password:","bent pipe"],
		"cpword":["Confirm Password:","Tourque"],
		"email":["Email:","CarKiller@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","tablet"],
		"friends":["I have:","25"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","Your car will never be the same"]
	},
"User 13" :{
		"group":["Group:","Phone Apps"],
		"fname":["First name:","Kelly"],
		"lname":["Last name:","Livingston"],
		"pword":["Password:","And Like"],
		"cpword":["Confirm Password:","And Like"],
		"email":["Email:","Don'tEvenGoThere@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","tablet"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","Don't you wanna' come party with me?"]
	},
"User 14" :{
		"group":["Group:","Phone Apps"],
		"fname":["First name:","The Tin"],
		"lname":["Last name:","Woodsman"],
		"pword":["Password:","oil can"],
		"cpword":["Confirm Password:","oil can"],
		"email":["Email:","INeedAHeart@aol.com"],
		"selectValue":["What do you want to do:","Multi-Text"],
		"deviceValue":["What device are you using:","phone"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","if I only had a heart"]
	},
"User 15" :{
		"group":["Group:","Manual Games"],
		"fname":["First name:","Scarecrow"],
		"lname":["Last name:","Of the cornfield"],
		"pword":["Password:","NoFire"],
		"cpword":["Confirm Password:","NoFire"],
		"email":["Email:","needABrain@aol.com"],
		"selectValue":["What do you want to do:","Multi-Text"],
		"deviceValue":["What device are you using:","phone"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","They tore off my arms and threw them over there!!"]
	},
"User 16" :{
		"group":["Group:","Card Games"],
		"fname":["First name:","The Cowardly"],
		"lname":["Last name:","Lion"],
		"pword":["Password:","I ain't scared a' nutin'"],
		"cpword":["Confirm Password:","I ain't scared a' nutin'"],
		"email":["Email:","putEmUp@aol.com"],
		"selectValue":["What do you want to do:","Multi-Text"],
		"deviceValue":["What device are you using:","phone"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","Whad' ya' have tp go and do that for?"]
	},
"User 17" :{
		"group":["Group:","Card Games"],
		"fname":["First name:","Dorothy"],
		"lname":["Last name:","Of Kansas"],
		"pword":["Password:","Toto"],
		"cpword":["Confirm Password:","Toto"],
		"email":["Email:","Kansas@aol.com"],
		"selectValue":["What do you want to do:","Multi-Text"],
		"deviceValue":["What device are you using:","phone"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","There's no place like home!"]
	},
"User 18" :{
		"group":["Group:","Card Games"],
		"fname":["First name:","The Wizard"],
		"lname":["Last name:","of Oz"],
		"pword":["Password:","Come back tomorrow"],
		"cpword":["Confirm Password:","Come back tomorrow"],
		"email":["Email:","NeverMindThatManBehindTheCurtain@aol.com"],
		"selectValue":["What do you want to do:","ComputerChallenge"],
		"deviceValue":["What device are you using:","pc"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","Nobody gets in to see the wizard, not no way, not no how!!"]
	},
"User 19" :{
		"group":["Group:","Card Games"],
		"fname":["First name:","Glenda"],
		"lname":["Last name:","The good witch"],
		"pword":["Password:","Be gone"],
		"cpword":["Confirm Password:","Be gone"],
		"email":["Email:","GoodWitches@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","tablet"],
		"friends":["I have:","10,000,000"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","Follow the yellow brick road"]
	},
"User 20" :{
		"group":["Group:","Manual Games"],
		"fname":["First name:","The Wicked Witch"],
		"lname":["Last name:","Of The West"],
		"pword":["Password:","My Little Pretty"],
		"cpword":["Confirm Password:","My Pretty"],
		"email":["Email:","WickedWitches@aol.com"],
		"selectValue":["What do you want to do:","Text"],
		"deviceValue":["What device are you using:","phone"],
		"friends":["I have:","3"],
		"date":["Date:","June 16, 2012"],
		"comments":["comments:","I'm melting!"]
	}
}

		